### ISSUE TITLE
CDN-friendly HTTP API

### ISSUE THREAD

**Issue by mildbyte** [splitgraph/seafowl#20]
Implement a read-only HTTP API that obeys HTTP cache semantics and can benefit from any CDN / cache like Varnish:

Client sends a query like:

```
GET /q/[SHA hash of the query text]
X-Seafowl-Query: [actual query text]
```

The server receives the query, checks it's a SELECT query, checks that the hash matches, executes it. It sends it back with an [ETag](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag) that is a function of the versions of all tables that participate in this query:

```
200 OK
[query results]
ETag: [hash of the version of the table(s)]
Cache-Control: max-age=3600 [optional]
```

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#directives

When the client's browser queries the data again, it can then pass the ETag to see if the query results have changed:

```
GET /q/[SHA hash of the query text]
X-Seafowl-Query: [actual query text]
If-None-Match: [etag]
```

Intermediate caches/CDNs might not even forward the query to the origin, instead serving it from cache if it's not stale. If it reaches the server, the server can cheaply revalidate the entry by recomputing the etag and responding with a `304 Not Modified` if the tables in the query haven't changed their versions (without having to execute the query).

This only works for `SELECT` queries. `INSERT` and other writes should come in via `POST` requests.

**Comment by mildbyte** [comment]
> We might be able to make the GET API more friendly without losing caching semantics. If the request is GET /q/SELECT%201 (i.e., the parameter is the raw query, not a hash), then we could hash the parameter and return a 301 redirect to GET /q/[hash]

That's a decent idea actually, though the 301 would have to indicate to the requester to not only resubmit to `GET /q/[hash]` but also include the query as a header or GET body. Is there a way to force a 301 / 307 to do that?

**Comment by milesrichardson** [comment]
I'm not aware of a way for the server to provide the client with a _new_ body to send. But a 307 redirect will [reuse the method and body ](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307) of the request, so it's not perfect but it works if the client provides a copy of the query in both the body and URL parameter (or even only in the body).

**Comment by milesrichardson** [comment]
There is [303 See Other](https://httpwg.org/specs/rfc7231.html#status.303) ([wiki](https://en.wikipedia.org/wiki/HTTP_303)) which is interesting but doesn't seem to allow changing the body of the next request. Worth a read though
