### ISSUE TITLE
Prevent full table scans that result in OOM

### ISSUE THREAD

**Issue by aleda145** [splitgraph/seafowl#258]
First, this is an awesome project, exactly what I was looking for!

I tried out the demo and then did a simple `SELECT * FROM supply_chains`, which made the fly.io instance OOM crash.

I'm curious if there is a way to prevent full table scans in some way? Or in general prevent queries that would result in an OOM crash. I have read through the docs but I might have missed something :smile_cat: 

It's absolutely reasonable to get a bigger machine to support those queries though, so this might be a moot point!

**Comment by tv42** [comment]
It wouldn't be very hard to generate the JSON in a streaming fashion, one datafusion batch at a time.
