### ISSUE TITLE
CREATE EXTERNAL TABLE with empty Parquet file fails with `Invalid data type for Delta Lake: Null`

### ISSUE THREAD

**Issue by mildbyte** [splitgraph/seafowl#423]
Using this Parquet file: [issue_reactions.parquet.tar.gz](https://github.com/splitgraph/seafowl/files/11593543/issue_reactions.parquet.tar.gz) (from a Splitgraph DDN export of an empty query result)

```sql
CREATE EXTERNAL TABLE tmp_pipboubhthuymqqp STORED AS PARQUET LOCATION 'path/to/issue_reactions.parquet';
```

results in this error:

```
Arrow error: Schema error: Invalid data type for Delta Lake: Null')
```

**Comment by gruuya** [comment]
Note that `CREATE EXTERNAL TABLE` statement goes through, the error occurs when trying to create an actual delta table (i.e. materialize it from the external table):
```bash
$ curl -i -H "Content-Type: application/json" http://127.0.0.1:8080/q -d@- <<EOF
{"query": "CREATE EXTERNAL TABLE test STORED AS PARQUET LOCATION '/Users/markogrujic/Downloads/issue_reactions.parquet'"}
EOF
HTTP/1.1 200 OK
content-type: application/octet-stream
vary: Authorization, Content-Type, Origin, X-Seafowl-Query
content-length: 0
date: Tue, 30 May 2023 08:23:21 GMT

$ curl -i -H "Content-Type: application/json" http://127.0.0.1:8080/q -d@- <<EOF
{"query": "CREATE TABLE test AS SELECT * FROM staging.test"}
EOF
HTTP/1.1 400 Bad Request
vary: Authorization, Content-Type, Origin, X-Seafowl-Query
content-length: 65
date: Tue, 30 May 2023 08:23:46 GMT

Arrow error: Schema error: Invalid data type for Delta Lake: Null
```

The reason is that delta-rs [does not handle](https://github.com/delta-io/delta-rs/blob/main/rust/src/delta_arrow.rs#L214-L300) `arrow_schema::datatype::DataType::Null`; in fact, a proper type for this case seems to be lacking in the Delta protocol itself: https://github.com/delta-io/delta/blob/master/PROTOCOL.md#schema-serialization-format

**Comment by milesrichardson** [comment]
> Note that CREATE EXTERNAL TABLE statement goes through, the error occurs when trying to create an actual delta table (i.e. materialize it from the external table):

Or maybe the fix is to simply short-circuit the import process to stop after `CREATE EXTERNAL TABLE`, and not return an error, since technically the table was created with the correct schema, and the error happened when trying to load (non-existent) rows into it. (IIUC)

**Comment by gruuya** [comment]
Just debuged in a more detailed manner; what happens is that the `ARROW:schema:` gets base64 decoded by `parquet` crate, and it basically contains the same data as shown in `pandas:` above it. In turn `arrow-ipc` decides that the column type is Null, which is the route of the issue.

Maybe pandas makes an erroneous encoding somehow (worth seeing whether we can bump the version in Splitgraph). Alternatively, `arrow-ipc`/`parquet` should use other information in such case to determine the column type (`parquet` has access to an object that has the proper schema but it never uses it).

**Comment by milesrichardson** [comment]
Thanks for debugging that. Your comment makes sense.

I'm in favor of bumping the version of pandas in Splitgraph and seeing if the bug is still present.

**Comment by gruuya** [comment]
Mitigated by upgrading pandas to 2.x over at Splitgraph.
