### ISSUE TITLE
rust s3

### ISSUE THREAD

**Issue by gedw99** [splitgraph/seafowl#464]
I have been using garage , which is a rust based s3.

It supports replication between datacenter and also tiering, so that you can keep your data origin at Backblaze.

fly.io is also doing a similar things now too: v

**Comment by gruuya** [comment]
I think this store type is already supported by the existing S3 config, like MinIO is
https://github.com/splitgraph/seafowl/blob/ddf9c899da60bfd7162f61e19cf454dfb7863e6e/tests/statements/mod.rs#L77-L83

Let me know if that's not the case.
