### ISSUE TITLE
Friendlier cached GET API

### ISSUE THREAD

**Issue by mildbyte** [splitgraph/seafowl#55]
If the GET API receives an unhashed SQL query in the URL (e.g. just urlencoded), hash it and redirect the user to the hashed endpoint), as per https://github.com/splitgraph/seafowl/issues/20#issuecomment-1204130690

Need to consider the fact that the redirect will only make sense if the client ends up sending the actual query in the GET body/header correctly. So we need to use a redirect that preserves the headers/body and the client needs to send the headers/body in the original request as well, potentially limiting the friendliness of this.

**Comment by tv42** [comment]
I've had good success with putting urlencoded JSON in a GET query argument. Simplest possible thing and works just right with caching. There's a size limit, but that's not really different from headers.

At least for Cloudflare, limits seem pretty much equal: 16 KB for url, 16 KB for a single header. https://developers.cloudflare.com/workers/platform/limits/#request-limits

**Comment by mildbyte** [comment]
Using just the URL for the query definitely sounds feasible in this case (when we were designing Seafowl first, we were worried about URL limits and inconsistent stories about what query length `fetch()` and intermediate caches/proxies can accept).

Though we just discovered in https://github.com/splitgraph/seafowl/issues/306 that Cloudflare will not cache CORS OPTIONS preflights, which is suboptimal for Seafowl instances that are supposed to scale to zero when idle. Even if a query result is cached by Cloudflare, a brand new browser visiting the page will still trigger a CORS preflight, waking up the instance and defeating the purpose of scaling to zero.

I think with using just the URL for the query we can make Seafowl requests be considered ["simple"](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#simple_requests) and browsers not sending a CORS preflight altogether.
